# Generated by Django 4.1.2 on 2023-04-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_products_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='follower',
        ),
    ]
