# Generated by Django 4.1.2 on 2023-04-24 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='follower',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
